//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS_SQL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderDetailComboes = new HashSet<OrderDetailCombo>();
        }
    
        public int ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public int IDCustomer { get; set; }
        public string Address { get; set; }
        public Nullable<int> IDPromotions { get; set; }
    
        public virtual DBCustomer DBCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailCombo> OrderDetailComboes { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
