//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS_SQL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailCombo
    {
        public int STT { get; set; }
        public int ID { get; set; }
        public int IDCombo { get; set; }
        public int Quantity { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual Order Order { get; set; }
    }
}
