//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS_SQL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int STT { get; set; }
        public int ID { get; set; }
        public Nullable<int> IDItems { get; set; }
        public Nullable<int> IDCombo { get; set; }
        public int Quantity { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual Items Items { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
